version: '3.4'
services:
    
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=rubiti
      - POSTGRES_PASSWORD=Ign#Cor83
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  app:
    build: .
    command: bash start.sh
    env_file:
      - .env
    volumes:
      - .:/ac_vale
      - gems:/gems
    ports:
      - "3006:3006"
    depends_on:
      - db

volumes:
  postgres:
  gems: